name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      - name: 缓存依赖
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 安装依赖
        run: yarn install

      - name: 代码检查
        run: yarn lint

      - name: 构建项目
        run: yarn build
      - name:部署到GitHub Pages
        if:github.ref=='ref/heads/develop'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vue 项目构建输出目录
          branch: gh-pages # 部署的目标分支